#!/usr/bin/env python3
#
# 1st line should be one of the following
#!/usr/bin/env python3
#!/usr/bin/env python
#
# Public Domain 7/2025 Wesley Ebisuzaki
#
# Python v3.6+ program for downloading data from the
# CORe (Conventional Observation Reanalysis) as stored
# NODD (NOAA Open Data Disemination) using the Google
# Cloud.  This program will allow you to download
# subsets of the archive using partial http downloading.
# on some systems, the top line should be #!/usr/bin/env python3
# on some systems, the top line should be #!/usr/bin/env python
#
# This program requires python v3.6+ to be installed and onpath.
#
# this code is based on get_gfs.pl (public domain 10/2006 Wesley Ebisuzaki) 
# translated to python imperfectly by Google Gemini, API modified to 
# fit the needs of CORe
#
# The partial http downloading method documented in
#
#   https://nomads.ncep.noaa.gov/info.php?page=fastdownload
#
# The method had to be modified for Google Cloud because this service only
# supports downloading one byte range at a time.  Typically web servers
# support downloading multiple ranges.
#
# As common with NCEP files, the index file is human readable and is generated by
#
#      $ wgrib2 grib_file > grib_file.idx
#
# This technique has been used since 2004 for downloading grib version 1 files.
# ECMWF supports this method by providing their index files.  Of course their 
# index files have a different format.
#
#
# Variables:
#
# The URL_TEMPLATE has to have the base URL
#   various date codes can be embedded into the URL_TEMPLATE
#   $YYYY  4 digit year code
#   $MM    2 digit month code, 01..12
#   $DD    2 digit day code
#   $HH    2 digit hour code
#
# The URL of the index file has to be obtained using $URL_TEMPLATE$INV_SUFFIX
# The URL of the data  file has to be obtained using $URL_TEMPLATE$GRB_SUFFIX
#
# MULTIRANGE is either True or False
#  most http servers can download sections of a flle (partial http downloading)
#  This is necessary for this program to work.
#   most of the servers will support downloading multiple sections with one call
#    ie MULTIRANGE = True
#   google cloud (7/2025) only supports downloading of a single section
#    ie MULTIRANGE = False
#
# Note: urllib does not support partial file downloading from ftp servers
#
# v1.0.0   8/28/2025
import os
import sys
import re
import urllib.request
import urllib.error
import time
import datetime

version="get_gfs.py v1.0.0 8/2025"
def get_gfs(action, time_str, nloop, dt, regex, outdir):
    """
    Downloads CORe files based on specified parameters, using urllib for HTTP requests.

    Args:
        action (str): dataset to download 
        time_str (str): YYYYMMDDHH format (e.g., '2006101800').
        nloop (int): number of times to download
        dt (int): Delta forecast hour/day/month
        regex (str): regular expression
        outdir (str): Directory to place the files.
    """

    INV_SUFFIX = '.idx'
    GRB_SUFFIX = '.grb'

    # google cloud does not support partial http from more than 1 range a time
    MULTIRANGE=False
    # MULTIRANGE=True

    # check if field has a .idx suffix
    is_idx = False
    strlen=len(action)
    if strlen > 4:
        if action[strlen-4:strlen] == r".idx":
            is_idx = True
            strlen -= 4
            action = action[0:strlen]

    # determine the type of date code
    if len(time_str) == 6:
        type_time='month'
        dt=max(dt,1)
        year = int(time_str[0:4])
        month = int(time_str[4:6])
        dt=max(dt,1)
        date = datetime.datetime.strptime(time_str, '%Y%m')
    elif len(time_str) == 8:
        type_time='day'
        dt=max(dt,1)
        date = datetime.datetime.strptime(time_str, '%Y%m%d')
    elif len(time_str) == 10:
        # CORe has a dt of 3 hours
        type_time='3hr'
        dt=max(dt,3)
        date = datetime.datetime.strptime(time_str, '%Y%m%d%H')
    else:
        print("bad time, must be YYYYMM, YYYYMMDD or YYYYMMDDHH")
        sys.exit(8)
    nloop = max(nloop, 1)

    URL_TEMPLATE=''
    if type_time == 'month':
        if action == 'flx':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/month/flx/$YYYY/flx.$YYYY$MM"
        if action == 'pgb':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/month/pgb/$YYYY/pgb.$YYYY$MM"
    if type_time == 'day':
        if action == 'flx':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/day/flx/$YYYY/$MM/flx.$YYYY$MM$DD"
        if action == 'pgb':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/day/pgb/$YYYY/$MM/pgb.$YYYY$MM$DD"
    if type_time == '3hr':
        if action == 'flx':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/3hour/flx/$YYYY/$MM/flx.$YYYY$MM$DD$HH"
        if action == 'pgb':
            URL_TEMPLATE="https://storage.googleapis.com/noaa-nws-ncep-core/grib/3hour/pgb/$YYYY/$MM/pgb.$YYYY$MM$DD$HH"

    if URL_TEMPLATE == '':
        print(f"Bad option: must be file-type(.idx) not {action}", file=sys.stderr)
        sys.exit(8)

    if regex.lower() == 'all':
        regex = r"."

#   make a list of the date codes to process

    dates=[]
    for i in range(nloop):
        if type_time == 'day':
            dates.append(date.strftime("%Y%m%d"))
            date += datetime.timedelta(days=dt)
        elif type_time == '3hr':
            dates.append(date.strftime("%Y%m%d%H"))
            date += datetime.timedelta(hours=dt)
        elif type_time == 'month':
            dates.append(date.strftime("%Y%m"))
            month += dt
            if month > 12:
                year += (month-1) // 12
                month = ((month-1) % 12) + 1
            date = datetime.datetime(year,month,1)

    print("times to process=",dates)

#   generate the URLs

    urls=[]
    for date in dates:
        YYYY = date[0:4]
        MM = date[4:6]
        DD = date[6:8]
        HH = date[8:10]
        url = URL_TEMPLATE.replace('$YYYY', YYYY).replace('${YYYY}', YYYY)
        url = url.replace('$MM', MM).replace('${MM}', MM)
        url = url.replace('$DD', DD).replace('${DD}', DD)
        url = url.replace('$HH', HH).replace('${HH}', HH)
        urls.append(url)
    print("URLS=", urls)

#   process the URLs
    for url in urls:
        file_name = os.path.basename(url+GRB_SUFFIX)

        inventory_url = url + INV_SUFFIX
        data_url = url + GRB_SUFFIX

        # Read the inventory
        inventory_lines = []
        try:
            with urllib.request.urlopen(inventory_url) as response:
                # Decode as UTF-8, assuming text content
                inventory_lines = response.read().decode('utf-8').strip().split('\n')
        except urllib.error.HTTPError as e:
            print(f"HTTP Error {e.code} getting inventory from {inventory_url}: {e.reason}", file=sys.stderr)
            print("Retrying after 20 seconds...", file=sys.stderr)
            time.sleep(20) # Simulate Perl's sleep on error
            continue # Skip to next url
        except urllib.error.URLError as e:
            print(f"URL Error getting inventory from {inventory_url}: {e.reason}", file=sys.stderr)
            print("Retrying after 20 seconds...", file=sys.stderr)
            time.sleep(20) # Simulate Perl's sleep on error
            continue # Skip to next url
        except Exception as e:
            print(f"An unexpected error occurred getting inventory from {inventory_url}: {e}", file=sys.stderr)
            print("Retrying after 20 seconds...", file=sys.stderr)
            time.sleep(20) # Simulate Perl's sleep on error
            continue # Skip to next url

        # if inventory, only print 1st file
        if is_idx:
            for line in inventory_lines:
                print(line)
            sys.exit(0)

        n_inv = len(inventory_lines);

        # find the start of the grib messages
        start_range = []
        for line in inventory_lines:
            parts = line.split(':', 3)
            if len(parts) >= 2:
                try:
                    start_range.append(int(parts[1]))
                except ValueError:
                    print(f"Fatal Error: problem parsing {inventory_url}", file=sys.stderr)
                    print(f"Fatal Error: Could not parse byte offset from line: {line}", file=sys.stderr)
                    sys.exit(8)

        # calculate the end of the grib message by looking at following grib messages
        # need to worry about submessages which have the same starting value
        # last end_range is set to -1
        end_range = []
        for i in range(n_inv):
            j = i+1
            while j < n_inv and start_range[i] == start_range[j]:
                j = j + 1
            if j == n_inv:
                end_range.append(-1)
            else:
                end_range.append(start_range[j]-1)

        data_range_parts = []
        last_from = -1
        last_to = -100

        for i in range(n_inv):
            line = inventory_lines[i]
            regex_match = re.search(regex, line) if regex != r"." else True
            if regex_match:
                print("match: ",line)
                current_from = start_range[i]
                current_to = end_range[i]
                if last_from != current_from:
                    if last_to + 1 == current_from:
                        # extend range
                        last_to = current_to
                    elif last_from == -1:
                        # 1st range
                        last_to = current_to
                        last_from = current_from
                    else:
                        # need to save range
                        if last_from >= last_to:
                            data_range_parts.append(f"{last_from}-")
                        else:
                            data_range_parts.append(f"{last_from}-{last_to}")
                        last_from = current_from
                        last_to = current_to

        # processing any remaining ranges
        if last_from != -1:
            if last_to == -1:
                data_range_parts.append(f"{last_from}-")
            else:
                data_range_parts.append(f"{last_from}-{last_to}")

        n_ranges = len(data_range_parts)
        if n_ranges == 0:
            print(f"No data to download for {url}", file=sys.stderr)
            continue

        # prepare for output
        output_filepath_tmp = os.path.join(outdir, file_name + ".tmp")
        output_filepath_final = os.path.join(outdir, file_name)

        if MULTIRANGE == False:
            with open(output_filepath_tmp, 'wb') as out_file:
                request = urllib.request.Request(data_url)
                for i in range(n_ranges):
                    print(">>> range = ",i,data_range_parts[i])
                    print('Range', f'bytes={data_range_parts[i]}')
                    request.add_header('Range', f'bytes={data_range_parts[i]}')
                    with urllib.request.urlopen(request) as response:
                        out_file.write(response.read())
            os.rename(output_filepath_tmp, output_filepath_final)
        else:
            range_header_value = ",".join(data_range_parts)
            print("range_header="+range_header_value)

            request = urllib.request.Request(data_url)
            request.add_header('Range', f'bytes={range_header_value}')
            print("Range header=",f'bytes={range_header_value}')

            try:
                print(f"Downloading {data_url} (range: bytes={range_header_value}) to {output_filepath_final}...")
                with urllib.request.urlopen(request) as response:
                    with open(output_filepath_tmp, 'wb') as out_file:
                        out_file.write(response.read())
                os.rename(output_filepath_tmp, output_filepath_final)
            except urllib.error.HTTPError as e:
                print(f"HTTP Error {e.code} getting file from {data_url}: {e.reason}", file=sys.stderr)
                if os.path.exists(output_filepath_tmp):
                    os.remove(output_filepath_tmp) # Clean up partial download
                sys.exit(e.code) # Exit with HTTP error code
            except urllib.error.URLError as e:
                print(f"URL Error getting file from {data_url}: {e.reason}", file=sys.stderr)
                if os.path.exists(output_filepath_tmp):
                    os.remove(output_filepath_tmp) # Clean up partial download
                sys.exit(1) # Generic error code for URL issues
            except Exception as e:
                print(f"An unexpected error occurred downloading file from {data_url}: {e}", file=sys.stderr)
                if os.path.exists(output_filepath_tmp):
                    os.remove(output_filepath_tmp) # Clean up partial download
                sys.exit(1) # Generic error code

        print(f"Finished processing {url}")

        # slow down next download so it doesn't appear to be denial of services attack
        time.sleep(2)
    print("finished downloads")


if __name__ == "__main__":
    if len(sys.argv) != 7:
        print(version)
        print("\nget_core.py FILETYPE DATE NLOOP DT REGEX DIRECTORY\n")
        print("   Download selected fields from the CORe archive on google cloud (NOAA Open Data Dissemination)")
        print("      This program downloads selected fields as determined by REGEX\n")
        print("   FILETYPE = pgb, pgb.idx, pressure level analyses/index (ensemble mean)")
        print("              flx, flx.idx, non-pressure level analyses/index (ensemble mean),")
        print("              MAYBE flx-mem, flx-mem.idx,  like flx/flx.idx except for ensemble members")
        print("              MAYBE flx-stats, flx-stats.idx,  ensemble statistics for flx files")
        print("              MAYBE spgb, spgb.idx, simle pressure level analyses for ensemble members")
        print("              MAYBE spgb-stats, spgb-stats.idx,  ensemble statistics for spgb files")
        print("   DATE =     for monthly files, use YYYYMM")
        print("              for daily files, use YYYYMMDD")
        print("              for 3hourly files, use YYYYMMDDYY")
        print("   NLOOP:     numnber of files to process is max(NLOOP,1)")
        print("   DT:        delta-time, units depend on the DATE (hours,days,months)")
        print("              for monthly files, delta-time is max(DT,1) months")
        print("              FUTURE for daily files, delta-time is max(DT,1) days, ")
        print("              for 3hourly files, delta-time is max(DT,3) hours")
        print("   REGEX: regular expression, use all for match all fields")
        print("          ex.  '(HGT|TMP)', 'HGT:500 mb'")
        print("          see *.idx to view the strings for matching")
        print("   DIRECTORY:  name of the directory in which to place the files")
        print("   Example: get_core.py flx.idx 195001 1 1 '(PRATE|TMP:2 m above ground)' .   print idx file")
        print("   Example: get_core.py flx 195001 1 1 '(PRATE|TMP:2 m above ground)' .")
        print("             returns precip and 2m temperature in flx.195001.grb")

        sys.exit(8)

    action = sys.argv[1]
    time_arg = sys.argv[2]
    nloop_arg = int(sys.argv[3])
    dt_arg = int(sys.argv[4])
    regex_arg = sys.argv[5]
    outdir_arg = sys.argv[6]

    get_gfs(action, time_arg, nloop_arg, dt_arg, regex_arg, outdir_arg)

